proyecto2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('ventas.urls'))),
]

ventas/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'ventas'


#urlconf
urlpatterns = [
    path('template', views.template, name='vacio'),
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('productos/', views.productos, name='productos'),
    path('clientes/', views.clientes, name='clientes'),
    path('facturas/', views.facturas, name='facturas'),

    # Borrar registros
    path('facturas/borrar/<int:factura_id>/', views.borrar_factura, name='borrar_factura'),
    path('clientes/borrar/<int:cliente_id>/', views.borrar_cliente, name='borrar_cliente'),
    path('productos/borrar/<int:producto_id>/', views.borrar_producto, name='borrar_producto'),

    # Editar registros
    path('facturas/editar/<int:factura_id>/', views.editar_factura, name='editar_factura'),
    path('clientes/editar/<int:cliente_id>/', views.editar_cliente, name='editar_cliente'),
    path('productos/editar/<int:producto_id>/', views.editar_producto, name='editar_producto'),

    # Reportes
    path('reportes/productos', views.reportes_productos, name='reportes_productos'),
    path('reportes/clientes', views.reportes_clientes, name='reportes_clientes'),
]

ventas/forms.py
from django import forms
from .models import Cliente, Producto, Factura
from django.core.exceptions import ValidationError

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

        widgets = {
            'nit': forms.TextInput(attrs={'class': 'yellow-color', 'placeholder': 'XXXX XXXX XXXX XXXX'}),
            'nombre': forms.TextInput(attrs={'class': 'yellow-color', 'placeholder': 'Nombre completo'}),
            'direccion': forms.TextInput(attrs={'class': 'yellow-color', 'placeholder': 'Direccion completa'}),
        }

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'red-color', 'placeholder': 'Nombre del producto'}),
            'descripcion': forms.TextInput(attrs={'class': 'red-color', 'placeholder': 'Descripcion del producto'}),
            'precio': forms.TextInput(attrs={'class': 'red-color', 'placeholder': 'XX.XX', 'type': 'number'}),
            'stock': forms.TextInput(attrs={'class': 'red-color', 'placeholder': 'XX...', 'type': 'number'}),
        }


class FacturaForm(forms.ModelForm):
    class Meta:
        model = Factura
        fields = ['maestro', 'detalle', 'cliente']

        widgets = {
            'maestro': forms.TextInput(attrs={'class': 'blue-color', 'placeholder': 'Maestro de la factura'}),
            'detalle': forms.Textarea(attrs={'class': 'blue-color', 'placeholder': 'producto, cantidad\nproducto, cantidad\n.....   , .....'}),
            'cliente': forms.Select(attrs={'class': 'blue-color'}),
        }

    def clean_detalle(self):
        detalle = self.cleaned_data['detalle']
        lines = detalle.split('\n')

        productos_vendidos = []

        for line in lines:
            # Dividir cada línea en producto y cantidad
            parts = line.split(',')

            if len(parts) != 2:
                raise ValidationError('Cada línea del detalle debe tener el formato "producto, cantidad".')

            producto_nombre = parts[0].strip()
            cantidad = parts[1].strip()

            # Verificar si el producto existe en la base de datos
            try:
                producto = Producto.objects.get(nombre=producto_nombre)
            except Producto.DoesNotExist:
                raise ValidationError(f'El producto "{producto_nombre}" no está registrado en la base de datos.')

            # Actualizar el stock del producto
            nuevo_stock = producto.stock - int(cantidad)
            if nuevo_stock < 0:
                raise ValidationError(f'No hay suficiente stock para el producto "{producto_nombre}".')

            producto.stock = nuevo_stock
            productos_vendidos.append(producto)

        # Actualizar el stock de los productos vendidos
        for producto in productos_vendidos:
            producto.save() # Actualizar el producto en la base de datos

        return detalle

class BusquedaFacturaForm(forms.Form):
    busqueda = forms.CharField(max_length=50, required=False, label='Busqueda por maestro',
                                widget=forms.TextInput(
                                   attrs={'class': 'form-field', 'placeholder': 'Buscar...'}
                                ))
    
class BusquedaProductoForm(forms.Form):
    busqueda = forms.CharField(max_length=50, required=False, label='Busqueda por nombre',
                                widget=forms.TextInput(
                                   attrs={'class': 'form-field', 'placeholder': 'Buscar...'}
                                ))
    
class BusquedaClienteForm(forms.Form):
    busqueda = forms.CharField(max_length=50, required=False, label='Busqueda por nit',
                                widget=forms.TextInput(
                                   attrs={'class': 'form-field', 'placeholder': 'Buscar...'}
                                ))

ventas/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages

from .models import Cliente, Producto, Factura, save_to_xml
from . import forms


def home(request):
    return render(request, 'home.html')


def template(request):
    return render(request, 'template.html')

# PRODUCTOS

def productos(request):

    formualario = forms.ProductoForm()
    formulario_busqueda = forms.BusquedaProductoForm(request.GET)

    if request.method == 'POST':
        formulario = forms.ProductoForm(request.POST)
        if formulario.is_valid():
            formulario.save()  # Guardar en la base de datos
            # Guardar en el archivo XML
            save_to_xml()
            messages.success(request, 'El producto se ha creado con éxito.')
            return redirect('ventas:productos')
        else:
            for field, errors in formulario.errors.items():
                for error in errors:
                    messages.error(request, f'Error en el campo {field}: {error}')
            return redirect('ventas:productos')

    if request.method == 'GET':
        orden = request.GET.get('orden', 'normal')

        productos = Producto.objects.all()

        # Lógica para ordenar los productos según el campo seleccionado
        if orden.lower() == 'nombre':
            productos = Producto.objects.all().order_by('nombre')
        elif orden.lower() == 'precio':
            productos = Producto.objects.all().order_by('precio')
        elif orden.lower() == 'stock':
            productos = Producto.objects.all().order_by('stock')

        # Lógica para realizar la búsqueda exacta por nombre
        if formulario_busqueda.is_valid():
            busqueda = formulario_busqueda.cleaned_data['busqueda']
            if busqueda:
                productos = productos.filter(nombre__iexact=busqueda)

        # Renderizar la plantilla con la lista de productos ordenada
        formulario = forms.ProductoForm()
        return render(request, 'productos.html', {'form': formulario, 'form_busqueda': formulario_busqueda, 'datos': productos, 'campo_orden': orden})

    productos = Producto.objects.all()
    return render(request, 'productos.html', {'form': formualario, 'datos': productos, 'campo_orden': 'normal'})

def borrar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto.delete()
    # Guardar en el archivo XML
    save_to_xml()
    return redirect('ventas:productos')

def editar_producto(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)

    if request.method == 'POST':
        form = forms.ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            # Guardar en el archivo XML
            save_to_xml()
            messages.success(request, 'El producto se ha editado con éxito.')
            return redirect('ventas:productos')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'Error en el campo {field}: {error}')
            return redirect('ventas:productos')
    else:
        form = forms.ProductoForm(instance=producto)

    return render(request, 'editar_producto.html', {'form': form, 'producto': producto})

# CLIENTES

def clientes(request):
    formulario = forms.ClienteForm()
    formulario_busqueda = forms.BusquedaClienteForm(request.GET)

    if request.method == 'POST':
        formulario = forms.ClienteForm(request.POST)
        if formulario.is_valid():
            formulario.save()  # Guardar en la base de datos
            # Guardar en el archivo XML
            save_to_xml()
            messages.success(request, 'El cliente se ha creado con éxito.')
            return redirect('ventas:clientes')
        else:
            for field, errors in formulario.errors.items():
                for error in errors:
                    messages.error(request, f'Error en el campo {field}: {error}')
            return redirect('ventas:clientes')

    if request.method == 'GET':
        orden = request.GET.get('orden', 'normal')

        clientes = Cliente.objects.all()

        # Lógica para ordenar los clientes según el campo seleccionado
        if orden.lower() == 'nombre':
            clientes = Cliente.objects.all().order_by('nombre')
        elif orden.lower() == 'direccion':
            clientes = Cliente.objects.all().order_by('direccion')
        elif orden.lower() == 'nit':
            clientes = Cliente.objects.all().order_by('nit')

        # Lógica para realizar la búsqueda exacta por nit
        if formulario_busqueda.is_valid():
            busqueda = formulario_busqueda.cleaned_data['busqueda']
            if busqueda:
                clientes = clientes.filter(nit__iexact=busqueda)

        # Renderizar la plantilla con la lista de clientes ordenada
        formulario = forms.ClienteForm()
        return render(request, 'clientes.html', {'form': formulario, 'form_busqueda': formulario_busqueda, 'datos': clientes, 'campo_orden': orden})

    clientes = Cliente.objects.all()
    return render(request, 'clientes.html', {'form': formulario, 'datos': clientes, 'campo_orden': 'normal'})

def borrar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)
    cliente.delete()
    # Guardar en el archivo XML
    save_to_xml()
    return redirect('ventas:clientes')

def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, id=cliente_id)

    if request.method == 'POST':
        form = forms.ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            # Guardar en el archivo XML
            save_to_xml()
            messages.success(request, 'El cliente se ha editado con éxito.')
            return redirect('ventas:clientes')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'Error en el campo {field}: {error}')
            return redirect('ventas:clientes')
    else:
        form = forms.ClienteForm(instance=cliente)

    return render(request, 'editar_cliente.html', {'form': form, 'cliente': cliente})

# FACTURAS
def facturas(request):
    formulario = forms.FacturaForm()
    formulario_busqueda = forms.BusquedaFacturaForm(request.GET)

    if request.method == 'POST':
        formulario = forms.FacturaForm(request.POST)
        if formulario.is_valid():
            cliente_proveido = formulario.cleaned_data['cliente']
            if cliente_proveido is None:
                formulario.cleaned_data['cliente'] = 'CF'
            formulario.save()
            # Guardar en el archivo XML
            save_to_xml()
            messages.success(request, 'La factura se ha creado con éxito.')
            return redirect('ventas:facturas')
        else:
            for field, errors in formulario.errors.items():
                for error in errors:
                    messages.error(request, f'Error en el campo {field}: {error}')
            return redirect('ventas:facturas')

    if request.method == 'GET':
        orden = request.GET.get('orden', 'normal')
        busqueda = request.GET.get('busqueda', '')

        facturas = Factura.objects.all()

        # Lógica para ordenar las facturas según el campo seleccionado
        if orden.lower() == 'maestro':
            facturas = Factura.objects.all().order_by('maestro')
        elif orden.lower() == 'fecha_factura':
            facturas = Factura.objects.all().order_by('fecha')

        # Lógica para realizar la búsqueda exacta por maestro
        if formulario_busqueda.is_valid():
            busqueda = formulario_busqueda.cleaned_data['busqueda']
            if busqueda:
                facturas = facturas.filter(maestro__iexact=busqueda)

        # Renderizar la plantilla con la lista de facturas ordenada
        formulario = forms.FacturaForm()
        return render(request, 'facturas.html', {'form': formulario, 'form_busqueda': formulario_busqueda, 'datos': facturas, 'campo_orden': orden})

    
    facturas = Factura.objects.all()
    return render(request, 'facturas.html', {'form': formulario, 'datos': facturas, 'campo_orden': 'normal'})

def borrar_factura(request, factura_id):
    factura = get_object_or_404(Factura, id=factura_id)
    factura.delete()
    # Guardar en el archivo XML
    save_to_xml()
    return redirect('ventas:facturas')

def editar_factura(request, factura_id):
    factura = get_object_or_404(Factura, id=factura_id)

    if request.method == 'POST':
        form = forms.FacturaForm(request.POST, instance=factura)
        if form.is_valid():
            form.save()
            # Guardar en el archivo XML
            save_to_xml()
            messages.success(request, 'La factura se ha editado con éxito.')
            return redirect('ventas:facturas')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'Error en el campo {field}: {error}')
            return redirect('ventas:facturas')
    else:
        form = forms.FacturaForm(instance=factura)

    return render(request, 'editar_factura.html', {'form': form, 'factura': factura})

# REPORTES
def reportes_productos(request):

    facturas = Factura.objects.all()

    # 10 productos más vendidos
    productos = {}
    for factura in facturas:
        detalle = factura.detalle.split('\n')
        for producto in detalle:
            nombre, cantidad = producto.split(',')
            if nombre in productos:
                productos[nombre] += int(cantidad)
            else:
                productos[nombre] = int(cantidad)

    # Ordenar
    productos = sorted(productos.items(), key=lambda x: x[1], reverse=True)[:10]

    # Obtener nombres y cantidades

ventas/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- PESTAÑA -->
    <title>{% block title %}Ventas{% endblock %}</title>
    <link rel="icon" href="https://i.imgur.com/AU5bd9D.png">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/alerts.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/input.css' %}">
    <link rel="stylesheet" href="{% static 'css/tabla.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- SCRIPTS -->
    <script src="https://kit.fontawesome.com/e63c20851b.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar">
        <a href="{% url 'ventas:home' %}">
            <img src="https://i.imgur.com/VeiVrel.png" alt="Logo">
        </a>
        <p>Ventas</p>
    </nav>

    <!-- Contenido -->
    <main>
        
        {% if messages %}
            <div class="alert-container {% if messages.0.tags %}{{ messages.0.tags }}{% endif %}">
                {% for message in messages %}
                <p class="alert-message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}

        {% block content %}{% endblock %}

    </main>

    <!-- Footer -->
    <footer>
        <p>Todos los derechos reservados</p>
    </footer>

    <!-- Scripts -->
    <script src="{% static 'js/alerts.js' %}"></script>
</body>

</html>

ventas/templates/clientes.html
{% extends 'base.html' %}

{% block title %}Ver clientes{% endblock %}

{% block content %}
    <div class="reporte">
        <div class="container">
            <a href="{% url 'ventas:reportes_clientes' %}">
                <button class="btn yellow-color">Clientes con más compras</button>
            </a>
        </div>
    </div>

    <div class="nuevo_registro yellow-color">
        <div class="entrada">
            <div class="form-datos">
                <div class="container">
                    <div class="heading">
                        <h1>Nuevo cliente</h1>
                    </div>

                    <form class="site-form" method="post" action="">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn yellow-color">Agregar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="tablero">
        <div class="manejo-datos">
            <div class="izq">
                <div class="input-decorado">
                    <form method="get">
                        {{ form_busqueda }}
                        <button type="submit" class="btn yellow-color">Buscar</button>
                    </form>
                </div>
            </div>
            <div class="der">
                <div class="select-input-decorado">
                    <select id="ordenarSelect" onchange="ordenarTabla()">
                        <option >Ordenar por</option>
                        <option value="normal">Normal</option>
                        <option value="nit">Nit</option>
                        <option value="nombre">Nombre</option>
                        <option value="direccion">Direccion</option>
                    </select>
                </div>
                </div>
            </div>
        </div>
        <div class="tabla-datos">
            <div class="container">
                <h2>Listado de clientes <small id="filter-table">orden: {{ campo_orden }}</small></h2>
                <ul class="responsive-table">
                    <li class="table-header yellow-header">
                        <div class="col col-3">Nit</div>
                        <div class="col col-3">Nombre</div>
                        <div class="col col-3">Direccion</div>
                        <div class="col col-1">Acciones</div>
                    </li>
                    {% for dato in datos %}
                        <li class="table-row">
                            <div class="col col-3" data-label="Nit">{{ dato.nit }}</div>
                            <div class="col col-3" data-label="Name">{{ dato.nombre }}</div>
                            <div class="col col-3" data-label="Adress">{{ dato.direccion }}</div>
                            <div class="col col-1" data-label="Actions">
                                <a href="{% url 'ventas:editar_cliente' dato.id %}" class="btn-editar"><i class="fas fa-edit"></i></a>
                                <a href="{% url 'ventas:borrar_cliente' dato.id %}" class="btn-borrar" onclick="return confirm('¿Estás seguro de que deseas borrar este cliente?')"><i class="fas fa-trash-alt"></i></a>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>

    <script>
        function ordenarTabla() {
            var selectBox = document.getElementById("ordenarSelect");
            var selectedValue = selectBox.value;  // Usar value en lugar de text

            // Redirigir a la misma página con el parámetro de orden
            var enlace = "{% url 'ventas:clientes' %}?orden=" + selectedValue;
            window.location.href = enlace;
        }
    </script>
{% endblock %}

ventas/templates/editar_cliente.html
{% extends 'base.html' %}

{% block title %}Editar cliente{% endblock %}

{% block content %}
<div class="edicion">
    <div class="form-datos">
        <div class="container">

            <div class="heading">
                <h1>Editar Cliente</h1>
            </div>

            <form method="post" action="{% url 'ventas:editar_cliente' cliente.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn yellow-color">Guardar cambios</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ventas/templates/editar_factura.html
{% extends 'base.html' %}

{% block title %}Editar factura{% endblock %}

{% block content %}
<div class="edicion">
    <div class="form-datos">
        <div class="container">

            <div class="heading">
                <h1>Editar Factura</h1>
            </div>

            <form method="post" action="{% url 'ventas:editar_factura' factura.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn blue-color">Guardar cambios</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ventas/templates/editar_producto.html
{% extends 'base.html' %}

{% block title %}Editar producto{% endblock %}

{% block content %}
<div class="edicion">
    <div class="form-datos">
        <div class="container">

            <div class="heading">
                <h1>Editar Producto</h1>
            </div>

            <form method="post" action="{% url 'ventas:editar_producto' producto.id %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn red-color">Guardar cambios</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ventas/templates/facturas.html
{% extends 'base.html' %}

{% block title %}Ver facturas{% endblock %}

{% block content %}
    
    <div class="nuevo_registro blue-color">
    <div class="entrada">
        <div class="form-datos">
            <div class="container">
                <div class="heading">
                    <h1>Nueva factura</h1>
                </div>
                
                <form class="site-form" method="post" action="{% url 'ventas:facturas' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn blue-color">Agregar</button>
                </form>

            </div>
        </div>
    </div>
    </div>

    <div class="tablero">
    <div class="manejo-datos">
        <div class="izq">
            <div class="input-decorado">
                <form method="get">
                    {{ form_busqueda }}
                    <button type="submit" class="btn blue-color">Buscar</button>
                </form>
            </div>
        </div>
        <div class="der">
            <div class="select-input-decorado">
                <select id="ordenarSelect" onchange="ordenarTabla()">
                    <option >Ordenar por</option>
                    <option value="normal">Normal</option>
                    <option value="maestro">Maestro</option>
                    <option value="fecha">Fecha factura</option>
                </select>
            </div>
        </div>
    </div>
    <div class="tabla-datos">
        <div class="container">
            <h2>Listado de clientes <small id="filter-table">orden: {{ campo_orden }}</small></h2>
            <ul class="responsive-table">
                <li class="table-header blue-header">
                    <div class="col col-3">Maestro</div>
                    <div class="col col-4">Detalle</div>
                    <div class="col col-2">Fecha</div>
                    <div class="col col-1">Acciones</div>
                </li>
                {% for dato in datos %}
                    <li class="table-row">
                        <div class="col col-3" data-label="Maestro">{{ dato.maestro }}</div>
                        <div class="col col-4" data-label="Detalle">{{ dato.detalle }}</div>
                        <div class="col col-2" data-label="Fecha">{{ dato.fecha }}</div>
                        <div class="col col-1" data-label="Actions">
                            <a href="{% url 'ventas:editar_factura' dato.id %}" class="btn-editar"><i class="fas fa-edit"></i></a>
                            <a href="{% url 'ventas:borrar_factura' dato.id %}" class="btn-borrar" onclick="return confirm('¿Estás seguro de que deseas borrar esta factura?')"><i class="fas fa-trash-alt"></i></a>
                        </div>

                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    </div>

    <script>
        function ordenarTabla() {
            var selectBox = document.getElementById("ordenarSelect");
            var selectedValue = selectBox.value;  // Usar value en lugar de text

            // Redirigir a la misma página con el parámetro de orden
            var enlace = "{% url 'ventas:facturas' %}?orden=" + selectedValue;
            window.location.href = enlace;
        }
    </script>

{% endblock %}

ventas/templates/productos.html
{% extends 'base.html' %}

{% block title %}Ver productos{% endblock %}

{% block content %}

    <div class="reporte">
        <div class="container">
            <a href="{% url 'ventas:reportes_productos' %}">
                <button class="btn red-color">Productos más vendidos</button>
            </a>
        </div>
    </div>

    <div class="nuevo_registro red-color">
    <div class="entrada">
        <div class="form-datos">
            <div class="container">
                <div class="heading">
                    <h1>Nuevo producto</h1>
                </div>

                <form class="site-form" method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn red-color">Agregar</button>
                </form>
            </div>
        </div>
    </div>
    </div>
    <div class="tablero">
    <div class="manejo-datos">
        <div class="izq">
            <div class="input-decorado">
                <form method="get">
                    {{ form_busqueda }}
                    <button type="submit" class="btn red-color">Buscar</button>
                </form>
            </div>
        </div>
        <div class="der">
            <div class="select-input-decorado">
                <select id="ordenarSelect" onchange="ordenarTabla()">
                    <option >Ordenar por</option>
                    <option value="normal">Normal</option>
                    <option value="nombre">Nombre</option>
                    <option value="precio">Precio</option>
                    <option value="stock">Stock</option>
                </select>
            </div>
        </div>
    </div>
    <div class="tabla-datos">
        <div class="container">
            <h2>Listado de productos <small id="filter-table">orden: {{ campo_orden }}</small></h2>
            <ul class="responsive-table">
                <li class="table-header red-header">
                    <div class="col col-2">Nombre</div>
                    <div class="col col-3">Descripción</div>
                    <div class="col col-2">Precio</div>
                    <div class="col col-2">Stock</div>
                    <div class="col col-1">Acciones</div>
                </li>
                {% for dato in datos %}
                    <li class="table-row">
                        <div class="col col-2" data-label="Nombre">{{ dato.nombre }}</div>
                        <div class="col col-3" data-label="Descripción">{{ dato.descripcion }}</div>
                        <div class="col col-2" data-label="Precio">{{ dato.precio }}</div>
                        <div class="col col-2" data-label="Stock">{{ dato.stock }}</div>
                        <div class="col col-1" data-label="Actions">
                            <a href="{% url 'ventas:editar_producto' dato.id %}" class="btn-editar"><i class="fas fa-edit"></i></a>
                            <a href="{% url 'ventas:borrar_producto' dato.id %}" class="btn-borrar" onclick="return confirm('¿Estás seguro de que deseas borrar este producto?')"><i class="fas fa-trash-alt"></i></a>
                        </div>
                    </li>
                {% endfor %}

            </ul>
        </div>
    </div>
    </div>

    <script>
        function ordenarTabla() {
            var selectBox = document.getElementById("ordenarSelect");
            var selectedValue = selectBox.value;  // Usar value en lugar de text

            // Redirigir a la misma página con el parámetro de orden
            var enlace = "{% url 'ventas:productos' %}?orden=" + selectedValue;
            window.location.href = enlace;
        }
    </script>

{% endblock %}

ventas/templates/reporte_clientes.html
{% extends 'base.html' %}

{% block title %}Clientes con más compras{% endblock %}

{% block content %}

    <div class="reporte-body">
        <h1>Productos más vendidos</h1>

        <div class="canvas-container">
            <canvas id="grafica"></canvas>
        </div>
    </div>

    <script>
        // Obtén los datos de Django y pásalos a JavaScript
        var nombresClientes = {{ nombres_clientes|safe }};
        var cantidadesCompras = {{ cantidades_compras|safe }};

        console.log(nombresClientes);
        console.log(cantidadesCompras);

        // Configura la gráfica
        var ctx = document.getElementById('grafica').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: nombresClientes,
                datasets: [{
                    label: 'Total de Compras realizadas',
                    data: cantidadesCompras,
                    backgroundColor: 'rgba(238, 202, 88, 0.5)',
                    borderColor: 'rgba(213, 176, 55, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>

{% endblock %}

ventas/templates/template.html
{% extends 'base.html' %}

{% block title %}Titulo pagina{% endblock %}

{% block content %}

{% endblock %}